apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketService-ticket-dply
  namespace: ticketService
  labels:
    app: ticketService-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketService-ticket
  template:
    metadata:
      labels:
        app: ticketService-ticket
    spec:
      containers:
      - image: ticketService.azurecr.io/ticketsvc
        name: ticketService-ticket
        env:
        - name: dbSvr
          valueFrom:
            configMapKeyRef:
              name: cm-ticketService
              key: dbSvr
        - name: dbUsr
          valueFrom:
            configMapKeyRef:
              name: cm-ticketService
              key: dbUsr              
        - name: dbPwd
          valueFrom:
            secretKeyRef:
              name: srt-ticketService
              key: dbPwd
        - name: rmqUsr
          valueFrom:
            configMapKeyRef:
              name: cm-ticketService
              key: rmqUsr              
        - name: rmqPwd
          valueFrom:
            secretKeyRef:
              name: srt-ticketService
              key: rmqPwd                        
        ports:
        - containerPort: 8080
          name: ticketService-ticket
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m          
---
apiVersion: v1
kind: Service
metadata:
  name: ticketsvc
  namespace: ticketService
  labels:
    app: ticketService-ticket
spec:
  selector:
    app: ticketService-ticket
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080